// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"net/http"
)

func Homepage(w http.ResponseWriter) {
	homepageLayout().Render(context.Background(), w)
}

func homepageLayout() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.WriteWatchModeString(templ_7745c5c3_Buffer, 1)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

// templ activeLayout(showTest bool) {
//
//				<p>Please only take the test once. Data will be available once all of it has been collected.</p>
//				if showTest {
//					<a href="/user">
//						<button class="bg-blue-600 text-white font-bold text-2xl p-5 rounded-xl transition-all hover:bg-blue-700 m-5">Start Test</button>
//					</a>
//				} else {
//					<button class="bg-gray-600 text-white font-bold text-2xl p-5 rounded-xl m-5" disabled>Test Complete</button>
//				}
//}
