// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.646
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/jackc/pgx/v5/pgxpool"
	"net/http"
)

func UserInfo(w http.ResponseWriter, db *pgxpool.Pool) {
	var id string
	err := db.QueryRow(context.Background(), "insert into users (name) values ($1) returning id", "test").Scan(&id)
	if err != nil {
		return
	}
	w.Header().Add("set-cookie", "eelsAAAId="+string(id)+";")

	infoPage(id).Render(context.Background(), w)
}

func infoPage(id string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><title>eelsAAA</title><script src=\"https://cdn.tailwindcss.com\"></script></head><body><div class=\"flex justify-center items-center flex-col w-full h-full\"><form class=\"flex flex-col justify-center\" action=\"/postUser\"><input type=\"hidden\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(id)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/user_info.templ`, Line: 28, Col: 36}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" id=\"id\" name=\"id\"><div class=\"flex m-5\"><div class=\"flex flex-col mx-1\"><label for=\"name\" class=\"text-right py-1\">Name: </label> <label for=\"age\" class=\"text-right mb-1\">Age: </label> <label for=\"l1\" class=\"text-right pt-1\">First Language: </label></div><div class=\"flex flex-col mx-1\"><input type=\"text\" id=\"name\" name=\"name\" class=\"border-2 rounded-lg border-gray-600 mb-1\"> <input type=\"number\" id=\"age\" name=\"age\" class=\"border-2 rounded-lg border-gray-600 mb-1\"> <input type=\"text\" id=\"l1\" name=\"l1\" class=\"border-2 rounded-lg border-gray-600\"></div></div><button input type=\"submit\" class=\"bg-blue-600 text-white font-bold text-xl shadow-md rounded-lg p-5\">Submit</button></form></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
