// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package graphs

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func generate(total int, inactive int, id string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_generate_f6ad`,
		Function: `function __templ_generate_f6ad(total, inactive, id){const svg = d3.select("#"+id)
    let width = 300,
        height = 300,
        radius = Math.min(width, height) / 2,
        g = svg.append("g").attr("transform", "translate(" + width / 2 + "," + height / 2 + ")")

  const pie = d3.pie()
  pie.padAngle(0.03)

  const arc = d3.arc().innerRadius(radius * 0.8).outerRadius(radius)

var color = d3.scaleOrdinal(['#4daf4a','#377eb8','#ff7f00','#984ea3','#e41a1c']);

  const arcs = g.selectAll("arc")
    .data(pie([inactive, total-inactive]))
    .enter()
    .append("g")
    .attr("inactive", "active")

  arcs.append("path")
    .attr("fill", function(d, i) {
      return color(i)
      })
    .attr("d", arc)

  arcs.append("text")
    .attr("transform", function(d){
        let pos = arc.centroid(d);
        let midangle = d.startAngle + (d.endAngle - d.startAngle) / 2
        pos[0] = radius * 0.4 * (midangle < Math.PI ? 1 : -1);
        return 'translate(' + pos + ')';
    })
    .attr("text-anchor", "middle")
    .text( function(d, i) {
      return [inactive + " inactive", (total-inactive) + " active"][i]}
    );


}`,
		Call:       templ.SafeScript(`__templ_generate_f6ad`, total, inactive, id),
		CallInline: templ.SafeScriptInline(`__templ_generate_f6ad`, total, inactive, id),
	}
}

func InactiveUsersPie(totalUsers int, inactiveUsers int) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = graphBase("Users", "", svgComponent("0 0 300 300", "users")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = generate(totalUsers, inactiveUsers, "users").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
